Adds the repack job for repackaging k8s releases
mbruzek/jenkins-jobs pull request #8
Opened 2016-10-31 18:50 UTC by chuckbutler

2016-10-31 19:16 UTC, mbruzek requested changes
I would like to see some changes in this request. Let me know if you disagree with my suggestions.

2016-10-31 19:16 UTC, mbruzek commented on kubernetes-upstream-repack/config.xml
> +          <defaultValue>https://github.com/kubernetes/kubernetes/releases/download/v1.4.4/kubernetes.tar.gz</defaultValue>
Could we build the URL with the $VERSION variable so it appears like the other builders?

2016-10-31 19:16 UTC, mbruzek commented on kubernetes-upstream-repack/config.xml
> +./package_kubernetes.sh $PWD/kubernetes.tar.gz.1</command>
Is this file name "kuberentes.tar.gz.1" correct here or is this a duplicate artifact of wget?

2016-10-31 19:16 UTC, mbruzek commented on kubernetes-upstream-repack/config.xml
> +        <credentialsId>jenkins_github_credential</credentialsId>
We can make the repo public if that is the only reason for your credentials here.

2016-10-31 19:16 UTC, mbruzek commented on kubernetes-upstream-repack/config.xml
> +wget $KUBERNETES_RESOURCE -o kubernetes.tar.gz
We should build the URL here from the $VERSION variable if possible.

2016-11-01 16:36 UTC, chuckbutler commented on kubernetes-upstream-repack/config.xml
> +./package_kubernetes.sh $PWD/kubernetes.tar.gz.1</command>
no, its kubernetes.tar.gz.1, and it baffled me... i think whats happening is wget is following the redirect and its getting both the html document and the package deliverable.

2016-11-01 16:36 UTC, chuckbutler commented on kubernetes-upstream-repack/config.xml
> +        <credentialsId>jenkins_github_credential</credentialsId>
thats fine, but it needs to happen before i remove credentials from the job. chicken/egg.

2016-11-01 16:37 UTC, chuckbutler commented on kubernetes-upstream-repack/config.xml
> +          <defaultValue>https://github.com/kubernetes/kubernetes/releases/download/v1.4.4/kubernetes.tar.gz</defaultValue>
certainly

2016-11-03 15:06 UTC, mbruzek commented
+1 This looks more like the others.

2016-11-03 15:07 UTC, merged